### ISSUE TITLE
Q4Wine on Ubuntu (Bug)

### ISSUE THREAD

**Issue by JoshMayBalGitHub** [brezerk/q4wine#195]
Q4wine in Ubuntu is outdated. Native release is only 1.3.12 when latest is 1.3.13.
Picture 1:
![Screenshot_20220521_002526](https://user-images.githubusercontent.com/93077235/169571376-d49fe92f-3161-4508-a60b-abd06f6879b2.png)
Picture 2:
![Screenshot_20220521_002611](https://user-images.githubusercontent.com/93077235/169571489-e456a75a-e8ff-44bd-bda8-ea5e2776a369.png)

pls fix

**Comment by rodin-ia** [comment]
hi, this is a question maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>

**Comment by brezerk** [comment]
hi @JoshMayBalGitHub thank you for bug report.

Yeah. As @rodin-ia mentioned this is up to package maintainer to keep distribution packages up to date. Please contact to respective package maintainers.

jfyi: Not saying this your case exactly, but I got some reports about maintainers delaying and sabotaging package upgrades because of my nationality (I am Ukrainian) like this one: https://src.fedoraproject.org/rpms/q4wine/pull-request/2  Unfortunately there is nothing I can do about this at this point.

Sorry for inconvenience. Thanks!

**Comment by tehnick** [comment]
@JoshMayBalGitHub Use official PPA for Ubuntu.

**Comment by tehnick** [comment]
@brezerk Why did you remove me from project?

**Comment by tehnick** [comment]
> https://src.fedoraproject.org/rpms/q4wine/pull-request/2

I have read this thread and do not see any references to problems with q4wine developers nationality. There is only understandable frustration of maintainer due to toxic conversation with hyper-active user.

**Comment by JoshMayBalGitHub** [comment]
> @JoshMayBalGitHub Use [official PPA](https://launchpad.net/~tehnick/+archive/ubuntu/q4wine) for Ubuntu.

ok thanks!
