### ISSUE TITLE
[Qt5] Winetricks application list fails to refresh and causes segfault on quit

### ISSUE THREAD

**Issue by sl1pkn07** [brezerk/q4wine#53]
in Qt5 port

when run the winetrick updater list, show the process window. but when finished don't display the list of apps/dll/etc in setup window

e53bf788c94a720a235d01bde03c1fbf556f0637 build with Qt5 5.4.1

greetings

**Comment by brezerk** [comment]
Hi. There is no Qt5 support in q4wine yet. Regardless to the ability to compile it with Qt5.

And I believe there will be no Qt5 support, at least for current code base. Which is ugly, terrible, illogical and chaotic. This is not surprising since q4wine was evolved from "qt hello world" application btw ;)

There are some plans for rewriting q4wine from scratch to solve a lot of architect issues, however currently I have no time and mood for this. Sorry.

So I think Qt5 build should be removed, to avoid any other confusions.

For now You need to use Qt4 builds, or if it does not meet your requirements: consider using another wine gui application: http://wiki.winehq.org/ThirdPartyApplications

**Comment by skybon** [comment]
@brezerk I strongly disagree. The current Qt 5 compiles, runs and is suitable for production use. The only bug out there is in the winetricks plugin and it is clearly not a showstopper.

**Comment by brezerk** [comment]
Should be fixed in: https://github.com/brezerk/q4wine/commit/96a5cd439f998347cec2a52d7c1d9fda870b2c3e

Reopen if needed.

**Comment by sl1pkn07** [comment]
yes, is fixed

tnx!
